### ISSUE TITLE
miReact running on a local computer problem

### ISSUE THREAD

**Issue by FedeOrse** [muhligs/miReact#4]
Hello. I am interested in analysing human datasets, so I was having a go with the ones located in miReact. I tried running the code on a 32GB machine but when I use the mireact() function I get this error: “sbatch is needed”. This isn’t being run on a cluster, so I wonder if there is a option in the function for not going through sbatch but running directly on the computer or a ‘NULL’ option? We aren’t worried about long runtimes. 
Thank you very much in advance!

**Comment by LGGray** [comment]
Hi there, I also encountered the same error running miReact on my HPC with Sun Grid Engine instead of Sbatch.
After following your changes, the program runs but does not generate the mirnaActivity.rds file as directed to in the command. Instead an e.Rdata file in created in the newly generated directory. 
I'm unsure if this file is the correct output.

Thanks!

**Comment by muhligs** [comment]
Hi, Please look in the generated folder for a file:  mailmessage.txt or Rscript-[jobid].out (if it is run as a job)

If it does not exist, the program broke in mireact.R after the e.Rdata file was prepared. 
Likely around where the Sbatch code is.

**Comment by LGGray** [comment]
Thank you for your reply.

The mailmessage.txt was generated and it looks like everything ran smoothly. 
Although `out.file ~/tools/miReact/data/mirnaActivity.rds` does not exist. 

Thanks

**Comment by muhligs** [comment]
In wrapper3.R, there are a number of print statements that reflects where in the process the program is, ending with 'Finished'. 
Did you see any of these prints to the console? It should hint at where the problem is. These statements usually end up in the Rscript-[jobid].out file, but may be directed elsewhere depending on how wrapper3.R is called. 

If these statements are not seen in your changed setup, you could insert a sink("statements.txt") and sink() in wrapper3.R to ensure that the statements are written to a file. If this is not clear, let me know and I will be explicit about where in wrapper3.R to put them.
